name: Genera PDF

on:
  push:
    branches: [ main ]
    paths:
      - 'slide/*.*'
      - '.github/workflows/generatepdf.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7

    - name: generate pdf
      run: |
        cd slide
        cp Corso_AI_Teoria.md Corso_AI_Teoria-backup.md
        sed -i "s/%date%/$(date +'%Y-%m-%d')/g" Corso_AI_Teoria.md
        sed -i "s/%time%/$(date +'%H:%M')/g" Corso_AI_Teoria.md
        npx @marp-team/marp-cli@latest Corso_AI_Teoria.md --pdf --allow-local-files
        rm Corso_AI_Teoria.md
        mv Corso_AI_Teoria-backup.md Corso_AI_Teoria.md

        cp Corso_AI_Pratica.md Corso_AI_Pratica-backup.md
        sed -i "s/%date%/$(date +'%Y-%m-%d')/g" Corso_AI_Pratica.md
        sed -i "s/%time%/$(date +'%H:%M')/g" Corso_AI_Pratica.md
        npx @marp-team/marp-cli@latest Corso_AI_Pratica.md --pdf --allow-local-files
        rm Corso_AI_Pratica.md
        mv Corso_AI_Pratica-backup.md Corso_AI_Pratica.md

    - name: commit & push
      run: |
        git add -A
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "update slides"
        git push
